sync with openbsd-current

diff --git a/etc/netstart b/etc/netstart
--- a/etc/netstart
+++ b/etc/netstart
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$OpenBSD: netstart,v 1.192 2018/02/17 13:11:03 rpe Exp $
+#	$OpenBSD: netstart,v 1.194 2018/02/19 23:42:29 rpe Exp $
 
 # Turn off Strict Bourne shell mode.
 set +o sh
@@ -84,11 +84,13 @@ vifscreate() {
 	local _vif _hn _if
 
 	for _vif in $(ifconfig -C); do
-		for _hn in /etc/hostname.${_vif}*; do
+		for _hn in /etc/hostname.${_vif}+([[:digit:]]); do
 			[[ -f $_hn ]] || continue
 			_if=${_hn#/etc/hostname.}
 
-			ifcreate $_if || return
+			if ! ifcreate $_if; then
+				print -u2 "${0##*/}: create for '$_if' failed."
+			fi
 		done
 	done
 }
@@ -104,14 +106,14 @@ ifstart() {
 	[[ $_if != +([[:alpha:]])+([[:digit:]]) ]] && return
 
 	if [[ ! -f $_hn ]]; then
-		echo "${0##*/}: $_hn: No such file or directory"
+		print -u2 "${0##*/}: $_hn: No such file or directory."
 		return
 	fi
 
 	# Not using stat(1), we can't rely on having /usr yet.
 	set -A _stat -- $(ls -nL $_hn)
 	if [[ "${_stat[0]}${_stat[2]}${_stat[3]}" != *---00 ]]; then
-		echo "WARNING: $_hn is insecure, fixing permissions"
+		print -u2 "WARNING: $_hn is insecure, fixing permissions."
 		chmod -LR o-rwx $_hn
 		chown -LR root:wheel $_hn
 	fi
@@ -149,9 +151,9 @@ ifmstart() {
 	local _sifs=$1 _xifs=$2 _hn _if _sif _xif
 
 	for _sif in ${_sifs:-ALL}; do
-		for _hn in /etc/hostname.*; do
+		for _hn in /etc/hostname.+([[:alpha:]])+([[:digit:]]); do
+			[[ -f $_hn ]] || continue
 			_if=${_hn#/etc/hostname.}
-			[[ $_if == '*' ]] && continue
 
 			# Skip unwanted ifs.
 			for _xif in $_xifs; do
